##### Import the Numpy package under the name np

In [38]:
import numpy as np

#### Print the numpy version and the configuration

In [39]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### Create a null vector of size 10

In [40]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### How to find the memory size of any array

In [41]:
array = np.zeros((100,100))
print("%d bytes" % (array.size * array.itemsize))

80000 bytes


####  How to get the documentation of the numpy add function from the command line?

##### Simply put this command on the terminal
###### python -c "import numpy as np; help(np.add)"

#### Create a null vector of size 10 but the fifth value which is 1

In [42]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Create a vector with values ranging from 10 to 49

In [43]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Reverse a vector (first element becomes last)

In [44]:
vector = np.arange(1,10)
reversed_vector = vector[::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [45]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [46]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


#### Create a 3x3 identity matrix

In [47]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create a 3x3x3 array with random values

In [48]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.36874005 0.72467489 0.94067556]
  [0.39635665 0.69564756 0.4375021 ]
  [0.47595853 0.50475853 0.64051408]]

 [[0.60347336 0.96442641 0.75052395]
  [0.2964764  0.31627092 0.09966419]
  [0.14473969 0.67874319 0.33702277]]

 [[0.17212117 0.33582269 0.33293029]
  [0.18306965 0.63194829 0.17385331]
  [0.45246902 0.20499467 0.62776906]]]


#### Create a random vector of size 30 and find the mean value

In [49]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)


0.4964513432490991


#### Create a 2D array with 1 on the border and 0 inside

In [50]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### How to add a border (filled with 0’s) around an existing array?

In [51]:
array = np.ones((3, 3))
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### What is the result of the following expression?

In [52]:
print(0 * np.nan)           # nan
print(np.nan == np.nan)     # False
print(np.inf > np.nan)      # False
print(np.nan - np.nan)      # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1)       # False

nan
False
False
nan
True
False


#### Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

In [53]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Create an 8x8 matrix and fill it with a checkerboard pattern

In [54]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [55]:
array = np.unravel_index(100, (6, 7, 8))
print(array)

(1, 5, 4)


#### Create a checkerboard 8x8 matrix using the tile function

In [56]:
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Normalize a 5x5 random matrix

In [57]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(normalized_matrix)

[[ 1.61013856 -0.67662521 -1.1340298  -0.89787592  1.66136984]
 [-0.1147399  -0.54455071 -0.06680751 -0.30309491 -1.37024443]
 [-0.43347321 -0.58534653 -0.58975215  1.53056284 -0.6470418 ]
 [-0.25616031 -0.64102336 -0.95874868  0.17822312 -0.92160128]
 [ 1.26087444  1.80068064  1.66980324  0.9843083  -0.55484523]]


#### Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [58]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\adity\AppData\Local\Temp\ipykernel_9592\295437610.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [59]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))
result = np.dot(matrix1, matrix2)
print(result)

[[1.06828431 0.27717748]
 [0.84160766 0.25875328]
 [0.57228136 0.11491036]
 [0.75329616 0.17964583]
 [0.28725409 0.03597719]]


#### Given a 1D array, negate all elements which are between 3 and 8, in place.

In [60]:
anjay = np.arange(11)
anjay[(3 < anjay) & (anjay <= 8)] *= -1
print(anjay)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### What is the output of the following script?

In [61]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### Consider an integer vector Z, which of these expressions are legal?

In [62]:
gggeming = np.arange(5)
print(gggeming**gggeming)
print(2 << gggeming >> 2)
print(gggeming < -gggeming)
print(1j*gggeming)
print(gggeming/1/1)
print(gggeming < gggeming > gggeming) #this is not legal


[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### What are the results of the following expressions?

In [63]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\adity\AppData\Local\Temp\ipykernel_9592\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\adity\AppData\Local\Temp\ipykernel_9592\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\adity\AppData\Local\Temp\ipykernel_9592\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### How to round away from zero a float array?

In [64]:
bro = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(bro)), bro))

[  5.  -9.  -3.   3.  -7.   9.   7.  -3.   1. -10.]


#### How to find common values between two arrays?

In [65]:
array1 = np.random.randint(0, 10, 10)
array2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(array1, array2)
print(common_values)

[0 7 9]
