##### Import the Numpy package under the name np

In [66]:
import numpy as np

#### Print the numpy version and the configuration

In [67]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### Create a null vector of size 10

In [68]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### How to find the memory size of any array

In [69]:
array = np.zeros((100,100))
print("%d bytes" % (array.size * array.itemsize))

80000 bytes


####  How to get the documentation of the numpy add function from the command line?

##### Simply put this command on the terminal
###### python -c "import numpy as np; help(np.add)"

#### Create a null vector of size 10 but the fifth value which is 1

In [70]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Create a vector with values ranging from 10 to 49

In [71]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Reverse a vector (first element becomes last)

In [72]:
vector = np.arange(1,10)
reversed_vector = vector[::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [73]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [74]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


#### Create a 3x3 identity matrix

In [75]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create a 3x3x3 array with random values

In [76]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.61791289 0.98988072 0.3999726 ]
  [0.14655894 0.50118192 0.9911442 ]
  [0.4908148  0.1552044  0.31262669]]

 [[0.68473564 0.07943489 0.87014363]
  [0.14327397 0.27734371 0.23605396]
  [0.70797583 0.74063531 0.09466974]]

 [[0.81253744 0.8135483  0.46448841]
  [0.31650089 0.0177341  0.04233664]
  [0.12647099 0.99906768 0.61465092]]]


#### Create a random vector of size 30 and find the mean value

In [77]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)


0.5468100182625509


#### Create a 2D array with 1 on the border and 0 inside

In [78]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### How to add a border (filled with 0’s) around an existing array?

In [79]:
array = np.ones((3, 3))
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### What is the result of the following expression?

In [80]:
print(0 * np.nan)           # nan
print(np.nan == np.nan)     # False
print(np.inf > np.nan)      # False
print(np.nan - np.nan)      # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1)       # False

nan
False
False
nan
True
False


#### Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

In [81]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Create an 8x8 matrix and fill it with a checkerboard pattern

In [82]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [83]:
array = np.unravel_index(100, (6, 7, 8))
print(array)

(1, 5, 4)


#### Create a checkerboard 8x8 matrix using the tile function

In [84]:
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Normalize a 5x5 random matrix

In [85]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(normalized_matrix)

[[-0.0098846  -0.12993256 -0.20635251 -1.48210324 -1.23795305]
 [ 0.67577807 -0.15697615  1.03037803 -1.56361735  1.34560418]
 [ 1.5075582  -1.25511711 -0.05941835 -0.53570879 -1.54418564]
 [ 0.28458294  1.71153581 -0.03047015  0.43707495  0.22879437]
 [ 0.26361692 -0.79253487  1.28608189  1.39259342 -1.15934441]]


#### Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [86]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\adity\AppData\Local\Temp\ipykernel_9592\295437610.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [87]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))
result = np.dot(matrix1, matrix2)
print(result)

[[0.26852301 0.31632821]
 [0.49280372 0.62787938]
 [0.77425214 0.88953524]
 [0.28544793 0.44458018]
 [0.72326353 0.79161896]]


#### Given a 1D array, negate all elements which are between 3 and 8, in place.

In [88]:
anjay = np.arange(11)
anjay[(3 < anjay) & (anjay <= 8)] *= -1
print(anjay)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### What is the output of the following script?

In [89]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


#### Consider an integer vector Z, which of these expressions are legal?

In [90]:
gggeming = np.arange(5)
print(gggeming**gggeming)
print(2 << gggeming >> 2)
print(gggeming < -gggeming)
print(1j*gggeming)
print(gggeming/1/1)
#print(gggeming < gggeming > gggeming) #this is not legal


[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### What are the results of the following expressions?

In [91]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\adity\AppData\Local\Temp\ipykernel_9592\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\adity\AppData\Local\Temp\ipykernel_9592\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\adity\AppData\Local\Temp\ipykernel_9592\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### How to round away from zero a float array?

In [92]:
bro = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(bro)), bro))

[ 2.  8.  8.  8.  7. -8.  6.  2.  4. -4.]


#### How to find common values between two arrays?

In [93]:
array1 = np.random.randint(0, 10, 10)
array2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(array1, array2)
print(common_values)

[0 1 2 7 8]


#### How to ignore all numpy warnings (not recommended)?

In [94]:
import warnings
warnings.filterwarnings('ignore')

#### Is the following expression true?

In [95]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### How to get the dates of yesterday, today, and tomorrow?

In [96]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2024-08-19 2024-08-20 2024-08-21
