##### Import the Numpy package under the name np

In [20]:
import numpy as np

#### Print the numpy version and the configuration

In [21]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### Create a null vector of size 10

In [22]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### How to find the memory size of any array

In [23]:
array = np.zeros((100,100))
print("%d bytes" % (array.size * array.itemsize))

80000 bytes


####  How to get the documentation of the numpy add function from the command line?

##### Simply put this command on the terminal
###### python -c "import numpy as np; help(np.add)"

#### Create a null vector of size 10 but the fifth value which is 1

In [24]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Create a vector with values ranging from 10 to 49

In [25]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Reverse a vector (first element becomes last)

In [26]:
vector = np.arange(1,10)
reversed_vector = vector[::-1]
print(reversed_vector)

[9 8 7 6 5 4 3 2 1]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [28]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


#### Create a 3x3 identity matrix

In [29]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create a 3x3x3 array with random values

In [30]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.41477393 0.7017489  0.88893178]
  [0.11407794 0.95648062 0.69576761]
  [0.3209168  0.137072   0.2559377 ]]

 [[0.60183934 0.84383458 0.8689305 ]
  [0.42024549 0.81318721 0.96885627]
  [0.74763313 0.27049203 0.69442331]]

 [[0.02141254 0.41167215 0.1470044 ]
  [0.8925599  0.50773993 0.26657783]
  [0.28031409 0.52845791 0.47129121]]]


#### Create a random vector of size 30 and find the mean value

In [31]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)


0.5543158578869006


#### Create a 2D array with 1 on the border and 0 inside

In [32]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### How to add a border (filled with 0’s) around an existing array?

In [33]:
array = np.ones((3, 3))
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### What is the result of the following expression?

In [34]:
print(0 * np.nan)           # nan
print(np.nan == np.nan)     # False
print(np.inf > np.nan)      # False
print(np.nan - np.nan)      # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1)       # False

nan
False
False
nan
True
False


#### Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

In [35]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Create an 8x8 matrix and fill it with a checkerboard pattern

In [36]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [37]:
array = np.unravel_index(100, (6, 7, 8))
print(array)

(1, 5, 4)
