In [1]:
import tensorflow as tf

In [2]:
# Scalar (0D tensor)
scalar = tf.constant(7)

# Vector (1D tensor)
vector = tf.constant([1, 2, 3, 4, 5])

# Matrix (2D tensor)
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tensor (3D tensor)
tensor = tf.constant([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]], 
    [[9, 10], [11, 12]]
])

In [3]:
# Shape
scalar_shape = scalar.shape
vector_shape = vector.shape
matrix_shape = matrix.shape
tensor_shape = tensor.shape

# Rank (Number of dimensions)
scalar_rank = tf.rank(scalar)
vector_rank = tf.rank(vector)
matrix_rank = tf.rank(matrix)
tensor_rank = tf.rank(tensor)

# Size (Total number of elements)
scalar_size = tf.size(scalar)
vector_size = tf.size(vector)
matrix_size = tf.size(matrix)
tensor_size = tf.size(tensor)

print(f"Scalar shape: {scalar_shape}, rank: {scalar_rank.numpy()}, size: {scalar_size.numpy()}")
print(f"Vector shape: {vector_shape}, rank: {vector_rank.numpy()}, size: {vector_size.numpy()}")
print(f"Matrix shape: {matrix_shape}, rank: {matrix_rank.numpy()}, size: {matrix_size.numpy()}")
print(f"Tensor shape: {tensor_shape}, rank: {tensor_rank.numpy()}, size: {tensor_size.numpy()}")

Scalar shape: (), rank: 0, size: 1
Vector shape: (5,), rank: 1, size: 5
Matrix shape: (3, 3), rank: 2, size: 9
Tensor shape: (3, 2, 2), rank: 3, size: 12


In [4]:
tensor_1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

In [5]:
# Matrix multiplication
result_matrix_multiplication = tf.matmul(tensor_1, tf.transpose(tensor_2))
result_matrix_multiplication


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.98278 , 72.1669  , 70.03015 , 76.63704 , 71.890144],
       [74.745605, 71.52576 , 66.587746, 77.06868 , 71.47607 ],
       [79.31361 , 75.87399 , 71.75935 , 79.37779 , 74.62061 ],
       [77.61182 , 74.76846 , 72.47418 , 75.80911 , 73.83296 ],
       [79.433464, 72.47853 , 74.68312 , 81.354805, 70.58197 ]],
      dtype=float32)>

In [6]:
# Element-wise multiplication (dot product)
result_dot_product = tf.multiply(tensor_1, tensor_2)
result_dot_product

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[2.28228897e-01, 5.85514605e-01, 6.52532816e-01, ...,
        4.01858896e-01, 5.53482056e-01, 1.19874543e-02],
       [7.84745887e-02, 2.35028844e-02, 4.51760679e-01, ...,
        3.48083884e-01, 2.36031323e-04, 4.64678667e-02],
       [1.90429807e-01, 5.42375565e-01, 1.22291092e-02, ...,
        5.40061951e-01, 1.25985503e-01, 1.19343875e-02],
       [3.50273866e-03, 1.54759243e-01, 1.30986437e-01, ...,
        3.08855146e-01, 1.02714263e-01, 2.59900093e-01],
       [1.37637988e-01, 1.53242841e-01, 4.59835947e-01, ...,
        6.26246929e-01, 1.37867406e-01, 5.40288806e-01]], dtype=float32)>

In [7]:
image_tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)

In [8]:
min_value = tf.reduce_min(image_tensor)
max_value = tf.reduce_max(image_tensor)

print(f"Min value: {min_value.numpy()}, Max value: {max_value.numpy()}")

Min value: 2.384185791015625e-06, Max value: 0.9999953508377075


In [9]:
tensor_to_squeeze = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
squeezed_tensor = tf.squeeze(tensor_to_squeeze)

print(f"Original shape: {tensor_to_squeeze.shape}")
print(f"Squeezed shape: {squeezed_tensor.shape}")

Original shape: (1, 224, 224, 3)
Squeezed shape: (224, 224, 3)


In [10]:
custom_tensor = tf.constant([3, 9, 1, 4, 8, 7, 2, 5, 6, 0])
max_index = tf.argmax(custom_tensor)

print(f"Tensor: {custom_tensor.numpy()}")
print(f"Index with maximum value: {max_index.numpy()}")

Tensor: [3 9 1 4 8 7 2 5 6 0]
Index with maximum value: 1


In [11]:
one_hot_encoded_tensor = tf.one_hot(custom_tensor, depth=10)

print(f"One-hot encoded tensor:\n{one_hot_encoded_tensor}")

One-hot encoded tensor:
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
# tf.image.random_flip_left_right documentation
"""
Ngebalikin sebuah gambar secara horizontal (kiri ke kanan) dengan peluang 50%.

Input:
- image: sebuah tensor (3d) dengan spesifikasi [height, width, channels].
  
Outpur:
- Tensor yang sama tipe, bedanya kebalik.
"""

image = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
flipped_image = tf.image.random_flip_left_right(image)


In [14]:
# Ngitung uang belajaan
prices = tf.constant([3.50, 4.20, 5.10, 2.35, 1.50])  # perkiraan harga

# Hitungan belanja
total_bill = tf.reduce_sum(prices)

# Hitungan belanja perbulan (kalo misal belanja tiap 4 minggu)
monthly_bill = total_bill * 4

# Hitungan belanja pertahun (12 bulan)
yearly_bill = monthly_bill * 12

print(f"Total bill for one trip: ${total_bill.numpy()}")
print(f"Total bill for the month: ${monthly_bill.numpy()}")
print(f"Total bill for the year: ${yearly_bill.numpy()}")


Total bill for one trip: $16.649999618530273
Total bill for the month: $66.5999984741211
Total bill for the year: $799.199951171875
